
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.RadioButton radiobutton1;

	private global::Gtk.RadioButton radiobutton2;

	private global::Gtk.HSeparator hseparator3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = "Permutation and Combination Calculator by Willy Susilo";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 16;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vbox4.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 20;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = "Pilih operasi perhitungan: ";
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.radiobutton1 = new global::Gtk.RadioButton("Permutasi");
		global::Gtk.Tooltips w3 = new Gtk.Tooltips();
		w3.SetTip(this.radiobutton1, "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item. Note: operasi permutas" +
				"i di kalkulator ini adalah permutasi tanpa pengulangan item yang sama.", "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item. Note: operasi permutas" +
				"i di kalkulator ini adalah permutasi tanpa pengulangan item yang sama.");
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.hbox1.Add(this.radiobutton1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobutton1]));
		w4.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.radiobutton2 = new global::Gtk.RadioButton("Kombinasi");
		w3.SetTip(this.radiobutton2, "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item yang unik (tanpa pengul" +
				"angan pola dengan item yang sama)", "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item yang unik (tanpa pengul" +
				"angan pola dengan item yang sama)");
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.hbox1.Add(this.radiobutton2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobutton2]));
		w5.Position = 2;
		this.vbox4.Add(this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.vbox4.Add(this.hseparator3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator3]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 838;
		this.DefaultHeight = 515;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
