
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.RadioButton radiobuttonP;

	private global::Gtk.RadioButton radiobuttonC;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label labelNR;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label3;

	private global::Gtk.SpinButton spinN;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label4;

	private global::Gtk.SpinButton spinR;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button buttonHitung;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Permutation and Combination Calculator by Willy Susilo");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 20;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 8;
		this.vbox4.BorderWidth = ((uint)(20));
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vbox4.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 20;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Pilih operasi perhitungan: ");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.radiobuttonP = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Permutasi"));
		global::Gtk.Tooltips w3 = new Gtk.Tooltips();
		w3.SetTip(this.radiobuttonP, "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item. Note: operasi permutas" +
				"i di kalkulator ini adalah permutasi tanpa pengulangan item yang sama.", "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item. Note: operasi permutas" +
				"i di kalkulator ini adalah permutasi tanpa pengulangan item yang sama.");
		this.radiobuttonP.CanFocus = true;
		this.radiobuttonP.Name = "radiobuttonP";
		this.radiobuttonP.DrawIndicator = true;
		this.radiobuttonP.UseUnderline = true;
		this.radiobuttonP.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.hbox1.Add(this.radiobuttonP);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonP]));
		w4.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.radiobuttonC = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Kombinasi"));
		w3.SetTip(this.radiobuttonC, "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item yang unik (tanpa pengul" +
				"angan pola dengan item yang sama)", "Merupakan operasi matematika untuk menghitung banyaknya kombinasi yang dapat dila" +
				"kukan dari sejumlah (n) set item dengan (r) sub-set item yang unik (tanpa pengul" +
				"angan pola dengan item yang sama)");
		this.radiobuttonC.CanFocus = true;
		this.radiobuttonC.Name = "radiobuttonC";
		this.radiobuttonC.DrawIndicator = true;
		this.radiobuttonC.UseUnderline = true;
		this.radiobuttonC.Group = this.radiobuttonP.Group;
		this.hbox1.Add(this.radiobuttonC);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonC]));
		w5.Position = 2;
		this.vbox4.Add(this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.vbox4.Add(this.hseparator3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator3]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Spacing = 8;
		this.vbox2.BorderWidth = ((uint)(20));
		// Container child vbox2.Gtk.Box+BoxChild
		this.labelNR = new global::Gtk.Label();
		this.labelNR.Name = "labelNR";
		this.labelNR.LabelProp = global::Mono.Unix.Catalog.GetString("N/A");
		this.vbox2.Add(this.labelNR);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelNR]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 8;
		this.hbox2.BorderWidth = ((uint)(12));
		// Container child hbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.WidthRequest = 400;
		this.label3.Name = "label3";
		this.label3.Xalign = 1F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Masukkan jumlah set (n): ");
		this.hbox2.Add(this.label3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.spinN = new global::Gtk.SpinButton(0D, 2147483647D, 1D);
		w3.SetTip(this.spinN, "Hanya bisa bilangan bulat positif", "Hanya bisa bilangan bulat positif");
		this.spinN.WidthRequest = 127;
		this.spinN.CanFocus = true;
		this.spinN.Name = "spinN";
		this.spinN.Adjustment.PageIncrement = 10D;
		this.spinN.ClimbRate = 1D;
		this.spinN.Numeric = true;
		this.hbox2.Add(this.spinN);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.spinN]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 8;
		this.hbox3.BorderWidth = ((uint)(12));
		// Container child hbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.WidthRequest = 400;
		this.label4.Name = "label4";
		this.label4.Xalign = 1F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Masukkan jumlah sub-set (r): ");
		this.hbox3.Add(this.label4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.spinR = new global::Gtk.SpinButton(0D, 2147483647D, 1D);
		w3.SetTip(this.spinR, "Nilai sub-set tidak bisa lebih dari nilai set. Hanya bisa bilangan bulat positif", "Nilai sub-set tidak bisa lebih dari nilai set. Hanya bisa bilangan bulat positif");
		this.spinR.WidthRequest = 127;
		this.spinR.CanFocus = true;
		this.spinR.Name = "spinR";
		this.spinR.Adjustment.PageIncrement = 10D;
		this.spinR.ClimbRate = 1D;
		this.spinR.Numeric = true;
		this.hbox3.Add(this.spinR);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spinR]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.buttonHitung = new global::Gtk.Button();
		this.buttonHitung.WidthRequest = 150;
		this.buttonHitung.HeightRequest = 50;
		this.buttonHitung.CanFocus = true;
		this.buttonHitung.Name = "buttonHitung";
		this.buttonHitung.UseUnderline = true;
		this.buttonHitung.Label = global::Mono.Unix.Catalog.GetString("Hitung");
		this.hbox4.Add(this.buttonHitung);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonHitung]));
		w17.Position = 1;
		w17.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 838;
		this.DefaultHeight = 515;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.radiobuttonP.Toggled += new global::System.EventHandler(this.OnRadiobuttonPToggled);
		this.spinN.Changed += new global::System.EventHandler(this.OnSpinNChanged);
		this.spinN.TextInserted += new global::Gtk.TextInsertedHandler(this.OnSpinNTextInserted);
		this.spinN.TextDeleted += new global::Gtk.TextDeletedHandler(this.OnSpinNTextDeleted);
	}
}
